package com.mustakim.bokbok.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

enum class AppTheme {
    CATPPUCCIN,
    GRUVBOX,
    MONOCHROME,
    NORD,
    TOKYO_NIGHT,
    DRACULA,
    SOLARIZED,
    ROSE_PINE,
    ONE_DARK,
    MATERIAL_CLASSIC
}

fun getDarkColorScheme(theme: AppTheme): ColorScheme = when (theme) {
    AppTheme.CATPPUCCIN -> darkColorScheme(
        primary = CatppuccinPrimaryDark,
        onPrimary = Color.Black,
        primaryContainer = Color(0xFF563E7C),
        onPrimaryContainer = CatppuccinPrimaryDark,
        secondary = CatppuccinSecondaryDark,
        onSecondary = Color.Black,
        secondaryContainer = Color(0xFF7C4764),
        onSecondaryContainer = CatppuccinSecondaryDark,
        tertiary = CatppuccinTertiaryDark,
        onTertiary = Color.Black,
        tertiaryContainer = Color(0xFF3E5978),
        onTertiaryContainer = CatppuccinTertiaryDark,
        background = CatppuccinBackgroundDark,
        onBackground = Color.White,
        surface = CatppuccinSurfaceDark,
        onSurface = Color.White,
        surfaceVariant = Color(0xFF3B3B4B),
        onSurfaceVariant = Color(0xFFCDD6F4),
        surfaceContainer = Color(0xFF2A2A3A),
        error = Color(0xFFF38BA8),
        onError = Color.Black,
        outline = Color(0xFF45475A),
        outlineVariant = Color(0xFF313244)
    )

    AppTheme.GRUVBOX -> darkColorScheme(
        primary = GruvboxPrimaryDark,
        onPrimary = Color.Black,
        primaryContainer = Color(0xFF7C5C28),
        onPrimaryContainer = GruvboxPrimaryDark,
        secondary = GruvboxSecondaryDark,
        onSecondary = Color.Black,
        secondaryContainer = Color(0xFF6F731E),
        onSecondaryContainer = GruvboxSecondaryDark,
        tertiary = GruvboxTertiaryDark,
        onTertiary = Color.White,
        tertiaryContainer = Color(0xFF9B2C24),
        onTertiaryContainer = GruvboxTertiaryDark,
        background = GruvboxBackgroundDark,
        onBackground = Color.White,
        surface = GruvboxSurfaceDark,
        onSurface = Color.White,
        surfaceVariant = Color(0xFF504945),
        onSurfaceVariant = Color(0xFFEBDBB2),
        surfaceContainer = Color(0xFF32302F),
        error = Color(0xFFCC241D),
        onError = Color.White,
        outline = Color(0xFF504945),
        outlineVariant = Color(0xFF3C3836)
    )

    AppTheme.MONOCHROME -> darkColorScheme(
        primary = MonochromePrimaryDark,
        onPrimary = Color.Black,
        primaryContainer = Color(0xFF4D4D4D),
        onPrimaryContainer = MonochromePrimaryDark,
        secondary = MonochromeSecondaryDark,
        onSecondary = Color.Black,
        secondaryContainer = Color(0xFF5E5E5E),
        onSecondaryContainer = MonochromeSecondaryDark,
        tertiary = MonochromeTertiaryDark,
        onTertiary = Color.White,
        tertiaryContainer = Color(0xFF333333),
        onTertiaryContainer = MonochromeTertiaryDark,
        background = MonochromeBackgroundDark,
        onBackground = Color.White,
        surface = MonochromeSurfaceDark,
        onSurface = Color.White,
        surfaceVariant = Color(0xFF2D2D2D),
        onSurfaceVariant = Color(0xFFCCCCCC),
        surfaceContainer = Color(0xFF0D0D0D),
        error = Color(0xFFFF4444),
        onError = Color.White,
        outline = Color(0xFF333333),
        outlineVariant = Color(0xFF1A1A1A)
    )

    AppTheme.NORD -> darkColorScheme(
        primary = NordPrimaryDark,
        onPrimary = Color.Black,
        primaryContainer = Color(0xFF4C7D94),
        onPrimaryContainer = NordPrimaryDark,
        secondary = NordSecondaryDark,
        onSecondary = Color.Black,
        secondaryContainer = Color(0xFF546E8B),
        onSecondaryContainer = NordSecondaryDark,
        tertiary = NordTertiaryDark,
        onTertiary = Color.White,
        tertiaryContainer = Color(0xFF3B4F73),
        onTertiaryContainer = NordTertiaryDark,
        background = NordBackgroundDark,
        onBackground = Color.White,
        surface = NordSurfaceDark,
        onSurface = Color.White,
        surfaceVariant = Color(0xFF434C5E),
        onSurfaceVariant = Color(0xFFECEFF4),
        surfaceContainer = Color(0xFF2E3440),
        error = Color(0xFFBF616A),
        onError = Color.White,
        outline = Color(0xFF4C566A),
        outlineVariant = Color(0xFF3B4252)
    )

    AppTheme.TOKYO_NIGHT -> darkColorScheme(
        primary = TokyoNightPrimaryDark,
        onPrimary = Color.Black,
        primaryContainer = Color(0xFF3D5A8E),
        onPrimaryContainer = TokyoNightPrimaryDark,
        secondary = TokyoNightSecondaryDark,
        onSecondary = Color.Black,
        secondaryContainer = Color(0xFF6A4C8E),
        onSecondaryContainer = TokyoNightSecondaryDark,
        tertiary = TokyoNightTertiaryDark,
        onTertiary = Color.White,
        tertiaryContainer = Color(0xFF94415C),
        onTertiaryContainer = TokyoNightTertiaryDark,
        background = TokyoNightBackgroundDark,
        onBackground = Color.White,
        surface = TokyoNightSurfaceDark,
        onSurface = Color.White,
        surfaceVariant = Color(0xFF292E42),
        onSurfaceVariant = Color(0xFFC0CAF5),
        surfaceContainer = Color(0xFF16161E),
        error = Color(0xFFF7768E),
        onError = Color.White,
        outline = Color(0xFF414868),
        outlineVariant = Color(0xFF24283B)
    )

    AppTheme.DRACULA -> darkColorScheme(
        primary = DraculaPrimaryDark,
        onPrimary = Color.Black,
        primaryContainer = Color(0xFF6D50A8),
        onPrimaryContainer = DraculaPrimaryDark,
        secondary = DraculaSecondaryDark,
        onSecondary = Color.Black,
        secondaryContainer = Color(0xFF994C87),
        onSecondaryContainer = DraculaSecondaryDark,
        tertiary = DraculaTertiaryDark,
        onTertiary = Color.Black,
        tertiaryContainer = Color(0xFF2E9B59),
        onTertiaryContainer = DraculaTertiaryDark,
        background = DraculaBackgroundDark,
        onBackground = Color.White,
        surface = DraculaSurfaceDark,
        onSurface = Color.White,
        surfaceVariant = Color(0xFF6272A4),
        onSurfaceVariant = Color(0xFFF8F8F2),
        surfaceContainer = Color(0xFF282A36),
        error = Color(0xFFFF5555),
        onError = Color.White,
        outline = Color(0xFF6272A4),
        outlineVariant = Color(0xFF44475A)
    )

    AppTheme.SOLARIZED -> darkColorScheme(
        primary = SolarizedPrimaryDark,
        onPrimary = Color.White,
        primaryContainer = Color(0xFF0F4D7D),
        onPrimaryContainer = SolarizedPrimaryDark,
        secondary = SolarizedSecondaryDark,
        onSecondary = Color.Black,
        secondaryContainer = Color(0xFF14615A),
        onSecondaryContainer = SolarizedSecondaryDark,
        tertiary = SolarizedTertiaryDark,
        onTertiary = Color.Black,
        tertiaryContainer = Color(0xFF4F5A00),
        onTertiaryContainer = SolarizedTertiaryDark,
        background = SolarizedBackgroundDark,
        onBackground = Color.White,
        surface = SolarizedSurfaceDark,
        onSurface = Color.White,
        surfaceVariant = Color(0xFF073642),
        onSurfaceVariant = Color(0xFF93A1A1),
        surfaceContainer = Color(0xFF002B36),
        error = Color(0xFFDC322F),
        onError = Color.White,
        outline = Color(0xFF586E75),
        outlineVariant = Color(0xFF073642)
    )

    AppTheme.ROSE_PINE -> darkColorScheme(
        primary = RosePinePrimaryDark,
        onPrimary = Color.Black,
        primaryContainer = Color(0xFF8B6478),
        onPrimaryContainer = RosePinePrimaryDark,
        secondary = RosePineSecondaryDark,
        onSecondary = Color.Black,
        secondaryContainer = Color(0xFF9C7042),
        onSecondaryContainer = RosePineSecondaryDark,
        tertiary = RosePineTertiaryDark,
        onTertiary = Color.Black,
        tertiaryContainer = Color(0xFF5A7F8C),
        onTertiaryContainer = RosePineTertiaryDark,
        background = RosePineBackgroundDark,
        onBackground = Color.White,
        surface = RosePineSurfaceDark,
        onSurface = Color.White,
        surfaceVariant = Color(0xFF26233A),
        onSurfaceVariant = Color(0xFFE0DEF4),
        surfaceContainer = Color(0xFF191724),
        error = Color(0xFFEB6F92),
        onError = Color.Black,
        outline = Color(0xFF403D52),
        outlineVariant = Color(0xFF26233A)
    )

    AppTheme.ONE_DARK -> darkColorScheme(
        primary = OneDarkPrimaryDark,
        onPrimary = Color.Black,
        primaryContainer = Color(0xFF3571A8),
        onPrimaryContainer = OneDarkPrimaryDark,
        secondary = OneDarkSecondaryDark,
        onSecondary = Color.Black,
        secondaryContainer = Color(0xFF7F4FA0),
        onSecondaryContainer = OneDarkSecondaryDark,
        tertiary = OneDarkTertiaryDark,
        onTertiary = Color.Black,
        tertiaryContainer = Color(0xFF578754),
        onTertiaryContainer = OneDarkTertiaryDark,
        background = OneDarkBackgroundDark,
        onBackground = Color.White,
        surface = OneDarkSurfaceDark,
        onSurface = Color.White,
        surfaceVariant = Color(0xFF2C313A),
        onSurfaceVariant = Color(0xFFABB2BF),
        surfaceContainer = Color(0xFF21252B),
        error = Color(0xFFE06C75),
        onError = Color.White,
        outline = Color(0xFF4B5263),
        outlineVariant = Color(0xFF2C313A)
    )

    AppTheme.MATERIAL_CLASSIC -> darkColorScheme(
        primary = MaterialPrimaryDark,
        onPrimary = Color.White,
        primaryContainer = Color(0xFF3700B3),
        onPrimaryContainer = MaterialPrimaryDark,
        secondary = MaterialSecondaryDark,
        onSecondary = Color.Black,
        secondaryContainer = Color(0xFF018786),
        onSecondaryContainer = MaterialSecondaryDark,
        tertiary = MaterialTertiaryDark,
        onTertiary = Color.White,
        tertiaryContainer = Color(0xFFB00020),
        onTertiaryContainer = MaterialTertiaryDark,
        background = MaterialBackgroundDark,
        onBackground = Color.White,
        surface = MaterialSurfaceDark,
        onSurface = Color.White,
        surfaceVariant = Color(0xFF2C2C2C),
        onSurfaceVariant = Color(0xFFE1E1E1),
        surfaceContainer = Color(0xFF1E1E1E),
        error = Color(0xFFCF6679),
        onError = Color.Black,
        outline = Color(0xFF3C3C3C),
        outlineVariant = Color(0xFF2C2C2C)
    )
}

fun getLightColorScheme(theme: AppTheme): ColorScheme = when (theme) {
    AppTheme.GRUVBOX -> lightColorScheme(
        primary = GruvboxPrimaryLight,
        onPrimary = Color.White,
        primaryContainer = Color(0xFFFFE4C4),
        onPrimaryContainer = Color(0xFF5F2100),
        secondary = GruvboxSecondaryLight,
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFE8F5C8),
        onSecondaryContainer = Color(0xFF3D4700),
        tertiary = GruvboxTertiaryLight,
        onTertiary = Color.White,
        tertiaryContainer = Color(0xFFFFDAD6),
        onTertiaryContainer = Color(0xFF5F0000),
        background = GruvboxBackgroundLight,
        onBackground = Color.Black,
        surface = GruvboxSurfaceLight,
        onSurface = Color.Black,
        surfaceVariant = Color(0xFFD5C4A1),
        onSurfaceVariant = Color(0xFF3C3836),
        surfaceContainer = Color(0xFFFBF1C7),
        surfaceContainerHigh = Color(0xFFEBDBB2),
        surfaceContainerHighest = Color(0xFFD5C4A1),
        error = Color(0xFF9D0006),
        onError = Color.White,
        outline = Color(0xFF928374),
        outlineVariant = Color(0xFFD5C4A1)
    )

    AppTheme.CATPPUCCIN -> lightColorScheme(
        primary = CatppuccinPrimaryLight,
        onPrimary = Color.White,
        primaryContainer = Color(0xFFE9D5FF),
        onPrimaryContainer = Color(0xFF5C0099),
        secondary = CatppuccinSecondaryLight,
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFFCE7F3),
        onSecondaryContainer = Color(0xFF8B005D),
        tertiary = CatppuccinTertiaryLight,
        onTertiary = Color.White,
        tertiaryContainer = Color(0xFFDBEAFE),
        onTertiaryContainer = Color(0xFF002D6E),
        background = CatppuccinBackgroundLight,
        onBackground = Color.Black,
        surface = CatppuccinSurfaceLight,
        onSurface = Color.Black,
        surfaceVariant = Color(0xFFDCE0E8),
        onSurfaceVariant = Color(0xFF4C4F69),
        surfaceContainer = Color(0xFFEFF1F5),
        surfaceContainerHigh = Color(0xFFE6E9EF),
        surfaceContainerHighest = Color(0xFFDCE0E8),
        error = Color(0xFFD20F39),
        onError = Color.White,
        outline = Color(0xFFACB0BE),
        outlineVariant = Color(0xFFDCE0E8)
    )

    AppTheme.MONOCHROME -> lightColorScheme(
        primary = MonochromePrimaryLight,
        onPrimary = Color.White,
        primaryContainer = Color(0xFFE0E0E0),
        onPrimaryContainer = Color(0xFF000000),
        secondary = MonochromeSecondaryLight,
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFD9D9D9),
        onSecondaryContainer = Color(0xFF1A1A1A),
        tertiary = MonochromeTertiaryLight,
        onTertiary = Color.White,
        tertiaryContainer = Color(0xFFCCCCCC),
        onTertiaryContainer = Color(0xFF333333),
        background = MonochromeBackgroundLight,
        onBackground = Color.Black,
        surface = MonochromeSurfaceLight,
        onSurface = Color.Black,
        surfaceVariant = Color(0xFFE8E8E8),
        onSurfaceVariant = Color(0xFF4D4D4D),
        surfaceContainer = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFF5F5F5),
        surfaceContainerHighest = Color(0xFFE8E8E8),
        error = Color(0xFFCC0000),
        onError = Color.White,
        outline = Color(0xFFAAAAAA),
        outlineVariant = Color(0xFFE0E0E0)
    )

    AppTheme.NORD -> lightColorScheme(
        primary = NordPrimaryLight,
        onPrimary = Color.White,
        primaryContainer = Color(0xFFD8DEE9),
        onPrimaryContainer = Color(0xFF2E3440),
        secondary = NordSecondaryLight,
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFE5E9F0),
        onSecondaryContainer = Color(0xFF2E3440),
        tertiary = NordTertiaryLight,
        onTertiary = Color.White,
        tertiaryContainer = Color(0xFFD8DEE9),
        onTertiaryContainer = Color(0xFF2E3440),
        background = NordBackgroundLight,
        onBackground = Color.Black,
        surface = NordSurfaceLight,
        onSurface = Color.Black,
        surfaceVariant = Color(0xFFD8DEE9),
        onSurfaceVariant = Color(0xFF3B4252),
        surfaceContainer = Color(0xFFECEFF4),
        surfaceContainerHigh = Color(0xFFE5E9F0),
        surfaceContainerHighest = Color(0xFFD8DEE9),
        error = Color(0xFFBF616A),
        onError = Color.White,
        outline = Color(0xFF8FBCBB),
        outlineVariant = Color(0xFFD8DEE9)
    )

    AppTheme.TOKYO_NIGHT -> lightColorScheme(
        primary = TokyoNightPrimaryLight,
        onPrimary = Color.White,
        primaryContainer = Color(0xFFDBE6FF),
        onPrimaryContainer = Color(0xFF001947),
        secondary = TokyoNightSecondaryLight,
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFF3E5FF),
        onSecondaryContainer = Color(0xFF4B0082),
        tertiary = TokyoNightTertiaryLight,
        onTertiary = Color.White,
        tertiaryContainer = Color(0xFFFFDAD6),
        onTertiaryContainer = Color(0xFF8C0009),
        background = TokyoNightBackgroundLight,
        onBackground = Color.Black,
        surface = TokyoNightSurfaceLight,
        onSurface = Color.Black,
        surfaceVariant = Color(0xFFBFC5D1),
        onSurfaceVariant = Color(0xFF3B4261),
        surfaceContainer = Color(0xFFD5D6DB),
        surfaceContainerHigh = Color(0xFFCBCCD1),
        surfaceContainerHighest = Color(0xFFBFC5D1),
        error = Color(0xFFE82424),
        onError = Color.White,
        outline = Color(0xFF8990A5),
        outlineVariant = Color(0xFFC3C9D8)
    )

    AppTheme.DRACULA -> lightColorScheme(
        primary = DraculaPrimaryLight,
        onPrimary = Color.White,
        primaryContainer = Color(0xFFEDEAFF),
        onPrimaryContainer = Color(0xFF3D2E5A),
        secondary = DraculaSecondaryLight,
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFFCE4FF),
        onSecondaryContainer = Color(0xFF6B2573),
        tertiary = DraculaTertiaryLight,
        onTertiary = Color.White,
        tertiaryContainer = Color(0xFFD1F4DD),
        onTertiaryContainer = Color(0xFF0A5224),
        background = DraculaBackgroundLight,
        onBackground = Color.Black,
        surface = DraculaSurfaceLight,
        onSurface = Color.Black,
        surfaceVariant = Color(0xFFD9D9D9),
        onSurfaceVariant = Color(0xFF4D4D4D),
        surfaceContainer = Color(0xFFF8F8F2),
        surfaceContainerHigh = Color(0xFFE6E6E6),
        surfaceContainerHighest = Color(0xFFD9D9D9),
        error = Color(0xFFCC0000),
        onError = Color.White,
        outline = Color(0xFFAAAAAA),
        outlineVariant = Color(0xFFD9D9D9)
    )

    AppTheme.SOLARIZED -> lightColorScheme(
        primary = SolarizedPrimaryLight,
        onPrimary = Color.White,
        primaryContainer = Color(0xFFDBE9FF),
        onPrimaryContainer = Color(0xFF001C3A),
        secondary = SolarizedSecondaryLight,
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFDBF5F0),
        onSecondaryContainer = Color(0xFF003731),
        tertiary = SolarizedTertiaryLight,
        onTertiary = Color.White,
        tertiaryContainer = Color(0xFFE5F1C3),
        onTertiaryContainer = Color(0xFF3A4400),
        background = SolarizedBackgroundLight,
        onBackground = Color.Black,
        surface = SolarizedSurfaceLight,
        onSurface = Color.Black,
        surfaceVariant = Color(0xFFE3DCC8),
        onSurfaceVariant = Color(0xFF657B83),
        surfaceContainer = Color(0xFFFDF6E3),
        surfaceContainerHigh = Color(0xFFEEE8D5),
        surfaceContainerHighest = Color(0xFFE3DCC8),
        error = Color(0xFFDC322F),
        onError = Color.White,
        outline = Color(0xFF93A1A1),
        outlineVariant = Color(0xFFE3DCC8)
    )

    AppTheme.ROSE_PINE -> lightColorScheme(
        primary = RosePinePrimaryLight,
        onPrimary = Color.White,
        primaryContainer = Color(0xFFFFE4E9),
        onPrimaryContainer = Color(0xFF6E3B52),
        secondary = RosePineSecondaryLight,
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFFFEBD6),
        onSecondaryContainer = Color(0xFF5F3D15),
        tertiary = RosePineTertiaryLight,
        onTertiary = Color.White,
        tertiaryContainer = Color(0xFFD8EAED),
        onTertiaryContainer = Color(0xFF2D4F56),
        background = RosePineBackgroundLight,
        onBackground = Color.Black,
        surface = RosePineSurfaceLight,
        onSurface = Color.Black,
        surfaceVariant = Color(0xFFF2E9E1),
        onSurfaceVariant = Color(0xFF575279),
        surfaceContainer = Color(0xFFFAF4ED),
        surfaceContainerHigh = Color(0xFFFFFAF3),
        surfaceContainerHighest = Color(0xFFF2E9E1),
        error = Color(0xFFB4637A),
        onError = Color.White,
        outline = Color(0xFF9893A5),
        outlineVariant = Color(0xFFF2E9E1)
    )

    AppTheme.ONE_DARK -> lightColorScheme(
        primary = OneDarkPrimaryLight,
        onPrimary = Color.White,
        primaryContainer = Color(0xFFDBE9FF),
        onPrimaryContainer = Color(0xFF002D6E),
        secondary = OneDarkSecondaryLight,
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFF3E5FF),
        onSecondaryContainer = Color(0xFF5D0070),
        tertiary = OneDarkTertiaryLight,
        onTertiary = Color.White,
        tertiaryContainer = Color(0xFFD1F4DD),
        onTertiaryContainer = Color(0xFF1A5228),
        background = OneDarkBackgroundLight,
        onBackground = Color.Black,
        surface = OneDarkSurfaceLight,
        onSurface = Color.Black,
        surfaceVariant = Color(0xFFE3E3E3),
        onSurfaceVariant = Color(0xFF526074),
        surfaceContainer = Color(0xFFFAFAFA),
        surfaceContainerHigh = Color(0xFFF0F0F0),
        surfaceContainerHighest = Color(0xFFE3E3E3),
        error = Color(0xFFBA2F3B),
        onError = Color.White,
        outline = Color(0xFFA0A7B8),
        outlineVariant = Color(0xFFE3E3E3)
    )

    AppTheme.MATERIAL_CLASSIC -> lightColorScheme(
        primary = MaterialPrimaryLight,
        onPrimary = Color.White,
        primaryContainer = Color(0xFFEADDFF),
        onPrimaryContainer = Color(0xFF21005D),
        secondary = MaterialSecondaryLight,
        onSecondary = Color.Black,
        secondaryContainer = Color(0xFFB2F1E8),
        onSecondaryContainer = Color(0xFF002020),
        tertiary = MaterialTertiaryLight,
        onTertiary = Color.White,
        tertiaryContainer = Color(0xFFFFDAD6),
        onTertiaryContainer = Color(0xFF93000A),
        background = MaterialBackgroundLight,
        onBackground = Color.Black,
        surface = MaterialSurfaceLight,
        onSurface = Color.Black,
        surfaceVariant = Color(0xFFE7E0EC),
        onSurfaceVariant = Color(0xFF49454F),
        surfaceContainer = Color(0xFFFFFBFE),
        surfaceContainerHigh = Color(0xFFF5F5F5),
        surfaceContainerHighest = Color(0xFFECE6F0),
        error = Color(0xFFB3261E),
        onError = Color.White,
        outline = Color(0xFF79747E),
        outlineVariant = Color(0xFFCAC4D0)
    )
}

